default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: intellart_development

test:
  <<: *default
  database: intellart_test

production:
  <<: *default
  database: intellart_production
  username: intellart
  password: <%= ENV['INTELLART_DATABASE_PASSWORD'] %>

staging:
  <<: *default
  database: intellart_be_staging
  username: deploy
  password: <%= ENV['INTELLART_DATABASE_PASSWORD'] %>
