default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: veritheum_development


test:
  <<: *default
  database: veritheum_test


production:
  <<: *default
  database: veritheum_production
  username: veritheum
  password: <%= ENV['VERITHEUM_DATABASE_PASSWORD'] %>

staging:
  <<: *default
  database: intellart_be_staging
  username: deploy
  password: <%= ENV['VERITHEUM_DATABASE_PASSWORD'] %>
